from typing import Dict, Any


class AnalysisService:
    """Service providing financial data formatting, ticker resolution, and summary utilities."""

    @staticmethod
    def format_disclaimer() -> str:
        return "\n\n*Disclaimer: This analysis is generated by AI using live financial data for educational purposes only and does not constitute financial, investment, or legal advice.*"
